[mypy]
python_version = 3.11
strict = True
exclude = (docs/source-materials/|_local/|tests/|alembic/|demos/)
warn_return_any = True
warn_unused_ignores = True
disallow_untyped_defs = True
disallow_any_generics = True
check_untyped_defs = True
no_implicit_reexport = True

[mypy-redis.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-pydantic.*]
ignore_missing_imports = True

[mypy-pydantic_settings.*]
ignore_missing_imports = True

[mypy-rich.*]
ignore_missing_imports = True

[mypy-typer.*]
ignore_missing_imports = True

[mypy-fastapi.*]
ignore_missing_imports = True

[mypy-uvicorn.*]
ignore_missing_imports = True

[mypy-jinja2.*]
ignore_missing_imports = True

[mypy-dashboard.*]
disallow_untyped_decorators = False

[mypy-aiohttp,aiosqlite,asyncpg,boto3,botocore.config,celery,celery.exceptions,celery.schedules,celery.signals,chromadb,chromadb.config,datasets,diffusers,docx,jose,langfuse,mlflow,nats,openpyxl,passlib.context,peft,pptx,psutil,pypdf,ray,torch,transformers,trl,wandb]
ignore_missing_imports = True
